#!/bin/bash
cdir = ~/.rip/
if [[ "$1" == "-gui" ]]; then
	w3m "http://viewdns.info/reverseip/?host=$2&t=1"; exit 1
fi
cd ~/.rip/
echo -n > ripHtml
curl "http://viewdns.info/reverseip/?host=$1&t=1" | grep '<table border="1">' >> ripHtml
python ripOrg.py