#!/bin/bash
v=false;gui=false
groupSearch=""; s=-s0
for i in $*; do
	case "$i" in
		"-gui")	gui=true;;
		"-v") v=true;;
		"-s"*) s=$i;;
		"-"*)	echo "Error:"+i+"isn't a command for this script."; exit 1;;
		*)	groupSearch=$groupSearch+$i;;
	esac
done
if [[ "$groupSearch" == "" ]]; then
	echo "Error: you didnt enter any search terms. Try again with some proper search terms."; exit 1
fi
groupSearch="$groupSearch"
if $gui; then
	w3m "http://viewdns.info/reversewhois/?q=$groupSearch"; exit 1
fi
if $v; then
	searchTerm=`curl -s "http://viewdns.info/reversewhois/?q=$groupSearch" | grep '<table border="1">'`
	python ~/.rip/ripWhois.py "$searchTerm" -web $s
else
	searchTerm=`curl "http://viewdns.info/reversewhois/?q=$groupSearch" | grep '<table border="1">'`
	python ~/.rip/ripWhois.py "$searchTerm" $s
fi
