#!/bin/bash

if [[ "$1" == "-gui" ]]; then
	w3m "http://viewdns.info/reversewhois/?q=$2+$3"; exit 1
fi
cd ~/.rip/
echo -n > ripHtml
curl "http://viewdns.info/reversewhois/?q=$1+$2" | grep '<table border="1">' >> ripHtml
python ripWhois.py
